name: Terraform plan and apply

on:
  workflow_call: 
    inputs:
      environment:
        description: 'Deployment environment (nonprd/preprd/prd)'
        type: string
        required: true
      deployment_target:
        description: 'Deployment target (central-comp)'
        type: string
        required: true
      opco:
        description: 'opco directory'
        type: string
        required: true
      mad_version:
        description: 'mad-core ref'
        type: string
        required: false
        default: 'main'
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Input
        shell: bash
        run: |
            pwd
            ls -l
            echo "reached mad-core"
            echo "Environment: ${{ inputs.environment }}"
            echo "Deployment Target: ${{ inputs.deployment_target }}"

      - uses: actions/checkout@v4
        name: mad-core checkout
        id: mad-core
        with:
          repository: vickydevopsorg/mad-core
          ref: ${{ inputs.mad_version }}
          path: mad-core
      
      - name: merge config
        id: config
        uses: ./.github/actions/merge-config
        with:
          source: ./${{ inputs.opco }}/${{ inputs.deployment_target }}/${{ inputs.environment }}-config.yaml
          target: ./${{ inputs.opco }}/${{ inputs.deployment_target }}/project-config.yaml

      - name: backend and config update
        shell: bash
        run: |
           echo "Updating backend"
           echo  ${{ inputs.opco }}/backends/${{ inputs.environment }}.tfbackend > mad-core/backends/${{ inputs.environment }}.tfbackend

           echo "Updating config"
           cat ${{ steps.config.outputs.config_path }} > mad-core/${{ inputs.deployment_target }}/config.yaml
    
      - name: Terraform Plan
        uses: ./.github/actions/terraform
        with:
          environment: ${{ inputs.environment }}
          tf_path: mad-core/${{ inputs.deployment_target }}