name: Terraform plan and apply

on:
  workflow_call: 
    inputs:
      environment:
        description: 'Deployment environment (nonprd/preprd/prd)'
        type: string
        required: true
      deployment_target:
        description: 'Deployment target (central-comp)'
        type: string
        required: true
      opco:
        description: 'opco directory'
        type: string
        required: true
      mad_version:
        description: 'mad-core ref'
        type: string
        required: false
        default: 'main'
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        name: mad-core checkout
        id: mad-core
        with:
          repository: vickydevopsorg/mad-core
          ref: ${{ inputs.mad_version }}
          path: mad-core

      # - name: merge config
      #   id: config
      #   uses: ./.github/actions/merge-config
      #   with:
      #     source: ./${{ inputs.opco }}/${{ inputs.deployment_target }}/${{ inputs.environment }}-config.yaml
      #     target: ./${{ inputs.opco }}/${{ inputs.deployment_target }}/project-config.yaml

      - name: merge-config
        id: config
        shell: bash
        run: |
          echo "config.yml update"
          yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' ./${{ inputs.opco }}/${{ inputs.deployment_target }}/${{ inputs.environment }}-config.yaml ./${{ inputs.opco }}/${{ inputs.deployment_target }}/project-config.yaml > final_config.yaml
          cat final_config.yaml > mad-core/${{ inputs.deployment_target }}/config.yaml

          echo "backend update"
          echo  ./${{ inputs.opco }}/backends/${{ inputs.environment }}.tfbackend > ./mad-core/backends/${{ inputs.environment }}.tfbackend
          
            
      - name: Temp- test
        run: |
            cd mad-core
            cat backends/nonprd.tfbackend
            cat central-comp/config.yaml
            ls -l

      # - name: backend and config update
      #   shell: bash
      #   run: |
      #      echo "Updating backend"
      #      ls -l
      #      echo  ./${{ inputs.opco }}/backends/${{ inputs.environment }}.tfbackend > ./mad-core/backends/${{ inputs.environment }}.tfbackend

      #      echo "Updating config"
      #      cat ${{ steps.config.outputs.config_path }} > mad-core/${{ inputs.deployment_target }}/config.yaml
    
      # - name: Terraform Plan
      #   uses: ./.github/actions/terraform
      #   with:
      #     environment: ${{ inputs.environment }}
      #     tf_path: mad-core/${{ inputs.deployment_target }}