name: Terraform plan and apply

on:
  workflow_call: 
    inputs:
      environment:
        description: 'Deployment environment (nonprd/preprd/prd)'
        required: true
      deployment_target:
        description: 'Deployment target (central-comp)'
        required: true
        default: 'central-comp'
      deploy_config:
        description: 'Deployment config'
        required: false
      backends_config:
        description: 'Backends config'
        required: false
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input
        shell: bash
        run: |
            echo "reached mad-core"
            echo "Environment: ${{ inputs.environment }}"
            echo "Deployment Target: ${{ inputs.deployment_target }}"
            echo "Deploy Config: ${{ inputs.deploy_config }}"
            echo "Backends Config: ${{ inputs.backends_config }}"